sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    max_update_rate: 0.2
    point_cloud_topic: /kinect2_victor_head/qhd/points
    max_range: 2.5
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
