header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
joint_names:
- 'victor_right_arm_joint_1'
- 'victor_right_arm_joint_2'
- 'victor_right_arm_joint_3'
- 'victor_right_arm_joint_4'
- 'victor_right_arm_joint_5'
- 'victor_right_arm_joint_6'
- 'victor_right_arm_joint_7'
points:
- positions: [0, 0, 0, 0, 0, 0, 0]
  velocities: []
  accelerations: []
  effort: []
  time_from_start: {secs: 0, nsecs: 0}
- positions: [0, 1, 0, 0, 0, 0, 0]
  velocities: []
  accelerations: []
  effort: []
  time_from_start: {secs: 1, nsecs: 0}
---
header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
joint_names:
- 'victor_left_arm_joint_1'
- 'victor_left_arm_joint_2'
- 'victor_left_arm_joint_3'
- 'victor_left_arm_joint_4'
- 'victor_left_arm_joint_5'
- 'victor_left_arm_joint_6'
- 'victor_left_arm_joint_7'
points:
- positions: [0, 0, 0, 0, 0, 0, 0]
  velocities: []
  accelerations: []
  effort: []
  time_from_start: {secs: 0, nsecs: 0}
- positions: [0, 1, 0, 0, 0, 0, 0]
  velocities: []
  accelerations: []
  effort: []
  time_from_start: {secs: 1, nsecs: 0}
