bool request_new
string robot_name
geometry_msgs/Point center
int64 w_cols
int64 h_rows
float32 resolution
float32 max_z
float32 min_z
---
int64 w_cols
int64 h_rows
float32[] sdf
std_msgs/Float64MultiArray gradient
float32[] res
int32[] origin
